- packages/backend/package-lock.json
- packages/backend/src/api.ts
- packages/backend/src/services/auth-service/adapters/msal.ts
- packages/backend/src/services/common/adapters/core-adapter.ts
- packages/backend/src/services/leasing-service/adapters/core-adapter.ts
- packages/backend/src/services/leasing-service/index.ts
- packages/backend/src/services/property-info-service/adapters/core-adapter.ts
- packages/backend/src/services/property-info-service/index.ts
- packages/frontend/.gitignore
- packages/frontend/package-lock.json
- packages/frontend/package.json
- packages/frontend/src/App.tsx
- packages/frontend/src/components/DataGridTable.tsx
- packages/frontend/src/index.css
- packages/frontend/src/pages/Parkingspaces/Index.tsx
- packages/frontend/tailwind.config.js
front och backend för att visa intresseanmälningar enligt: https://dev.azure.com/mimeronline/ONECore/_boards/board/t/Uthyrning/Issues/?workitem=1229
Jag refaktorerade kopplingen mot onecore-core så att vi kan dela utility-funktionen för åtkomst mellan tjänster. Tidigare fanns bara koppling mot onecore-property-management i detta projekt men nu behövde vi även koppla upp oss mot onecore-leasing. 
Det finns en todo i koden för att mappa typer från oneocore-types men för att inte stöka till det lägger jag det i ett separat kort så att vi kan göra det när https://dev.azure.com/mimeronline/ONECore/_boards/board/t/Uthyrning/Issues/?workitem=1217 är mergad. Jag la till detta som ett eget kort https://dev.azure.com/mimeronline/ONECore/_boards/board/t/Uthyrning/Issues/?workitem=1346. Denna branch …
> feat: 1229 list parking space applications

- packages/frontend/src/components/DataGridTable.tsx
- packages/frontend/src/pages/ParkingSpace/index.tsx
- packages/frontend/src/pages/ParkingSpaces/index.tsx
- packages/frontend/src/utils/debounce.ts
- packages/frontend/src/utils/index.ts
- Adds search bar
- Filter listings by applicant contact code
- Custom empty msg on datagrid
> feat: 1378 - search applicants listings

- packages/frontend/package-lock.json
- packages/frontend/package.json
- packages/frontend/src/pages/ParkingSpaces/index.tsx
- Filters listings by applicants national registration number
fixes [1428](https://dev.azure.com/mimeronline/ONECore/_boards/board/t/Uthyrning/Issues/?workitem=1428)
> feat: 1428 - filter listings by applicants nat reg number

- packages/backend/package-lock.json
- packages/backend/package.json
- packages/backend/src/services/leasing-service/adapters/core-adapter.ts
- packages/frontend/package-lock.json
- packages/frontend/package.json
- packages/frontend/src/pages/ParkingSpace/hooks/useParkingSpaceListing.ts
https://dev.azure.com/mimeronline/ONECore/_boards/board/t/Uthyrning/Issues/?workitem=1467
> feat: 1467 use detailed applicant response type

- packages/frontend/src/App.tsx
- packages/frontend/src/components/SiteHeader.tsx
* Added parking spaces as a menu option
* Set parking space page as home page
> Fix Menu with Parking Spaces

- packages/backend/package-lock.json
- packages/backend/package.json
- packages/backend/src/services/leasing-service/adapters/core-adapter.ts
- packages/backend/src/services/leasing-service/index.ts
- packages/frontend/package-lock.json
- packages/frontend/package.json
- packages/frontend/src/components/Carousel.tsx
- packages/frontend/src/pages/ParkingSpaces/components/create-applicant-for-listing/ContactInfo.tsx
- packages/frontend/src/pages/ParkingSpaces/components/create-applicant-for-listing/CreateApplicantForListing.tsx
- packages/frontend/src/pages/ParkingSpaces/components/create-applicant-for-listing/ListingInfo.tsx
- packages/frontend/src/pages/ParkingSpaces/hooks/useContactByContactCode.ts
- packages/frontend/src/pages/ParkingSpaces/hooks/useCreateApplicantForListing.ts
- packages/frontend/src/pages/ParkingSpaces/hooks/useTenantWithValidation.ts
- packages/frontend/src/theme.ts
- Adds property and residential validation when creating applicant for listing
**TODO:** 
- Add general error handling on the contact query endpoint consuming component
- Handle all responses from core. 403, 404 etc.
~- Generalise Tenant type. Its currently copied from leasing~
> 1560 - Apply area and address specific rental property rules when creating applicant

- packages/backend/package-lock.json
- packages/backend/package.json
- packages/backend/src/services/leasing-service/adapters/core-adapter.ts
- packages/backend/src/services/leasing-service/index.ts
- packages/frontend/package-lock.json
- packages/frontend/package.json
- packages/frontend/src/pages/ParkingSpace/hooks/useParkingSpaceListing.ts
- packages/frontend/src/pages/ParkingSpaces/components/SyncInternalParkingSpaces.tsx
- packages/frontend/src/pages/ParkingSpaces/components/create-applicant-for-listing/SyncInternalParkingSpaces.tsx
- packages/frontend/src/pages/ParkingSpaces/hooks/useSyncInternalParkingSpaces.ts
- packages/frontend/src/pages/ParkingSpaces/index.tsx
Adds a sync button + dialog to sync internal parking spaces from xpand.
> MIM-15: Synka leasing db med publicerade bilplatser från xpand

- packages/backend/src/services/leasing-service/adapters/core-adapter.ts
- packages/backend/src/services/leasing-service/index.ts
- packages/frontend/src/pages/ParkingSpace/components/RemoveApplicantFromListing.tsx
- packages/frontend/src/pages/ParkingSpace/hooks/useRemoveApplicantFromListing.tsx
- packages/frontend/src/pages/ParkingSpaces/components/DeleteListing.tsx
- packages/frontend/src/pages/ParkingSpaces/components/SyncInternalParkingSpaces.tsx
- packages/frontend/src/pages/ParkingSpaces/components/create-applicant-for-listing/CreateApplicantForListing.tsx
- packages/frontend/src/pages/ParkingSpaces/hooks/useDeleteParkingSpaceListing.ts
- packages/frontend/src/pages/ParkingSpaces/index.tsx
Adds button and dialog for deleting a listing. Only works if listing isnt reference by other entities.
> MIM-87: Delete listing

- packages/backend/src/services/leasing-service/adapters/core-adapter.ts
Use content prop from core response when fetching validation
> fix: use content when fetching from core

- packages/backend/src/services/leasing-service/adapters/core-adapter.ts
- packages/backend/src/services/leasing-service/index.ts
- packages/frontend/package-lock.json
- packages/frontend/package.json
- packages/frontend/src/components/Tabs.tsx
- packages/frontend/src/components/index.ts
- packages/frontend/src/pages/ParkingSpace/index.tsx
- packages/frontend/src/pages/ParkingSpaces/components/DeleteListing.tsx
- packages/frontend/src/pages/ParkingSpaces/components/create-applicant-for-listing/CreateApplicantForListing.tsx
- packages/frontend/src/pages/ParkingSpaces/hooks/useParkingSpaceListings.ts
- packages/frontend/src/pages/ParkingSpaces/index.tsx
- Adds tabs to listings and queries based on query param "type"
- Rename listing column "typ" to "kötyp"
- Column "bilplatstyp" now shows "objectTypeCaption" instead of "rentalObjectTypeCaption"
- Rename delete listing copy from "Ta bort" to "Ta bort annons"
> MIM-157: Tabs for types of listings

- packages/backend/package-lock.json
- packages/backend/package.json
- packages/backend/src/services/leasing-service/adapters/core-adapter.ts
- packages/backend/src/services/leasing-service/index.ts
- packages/frontend/package.json
- packages/frontend/src/pages/ParkingSpaces/components/create-applicant-for-listing/CreateApplicantForListing.tsx
- packages/frontend/src/pages/ParkingSpaces/hooks/useCreateApplicantForListing.ts
- packages/frontend/src/pages/ParkingSpaces/hooks/useCreateNoteOfInterest.ts
- packages/frontend/src/types.ts
https://linear.app/mimer-onecore/issue/MIM-36/skapa-intresseanmalan-ge-ratt-felsvar-till-sokande
> MIM-36: render error if credit check fails

- packages/backend/package-lock.json
- packages/backend/package.json
- packages/backend/src/services/leasing-service/adapters/core-adapter.ts
- packages/backend/src/services/leasing-service/index.ts
- packages/frontend/package-lock.json
- packages/frontend/package.json
- packages/frontend/src/pages/ParkingSpaces/hooks/useParkingSpaceListings.ts
- packages/frontend/src/pages/ParkingSpaces/index.tsx
https://linear.app/mimer-onecore/issue/MIM-171/fixa-till-befintliga-listings-flikar
> MIM-171: "Erbjudna" tab should show offer expire date

- packages/frontend/src/pages/ParkingSpace/index.tsx
https://linear.app/mimer-onecore/issue/MIM-199/medarbetarportalen-bilplatssidan-visa-fliken-senaste-omgangen-nar-man
> MIM-199: set default tab to last offer if listing has offers

- packages/frontend/src/pages/ParkingSpaces/index.tsx
* An error formatted and friendly message is displayed to the user on any unexpected errors when getting the parking spaces
> Feat:UTH-106 Error Handling When Getting Parking Spaces

- packages/frontend/src/pages/ParkingSpaces/components/create-applicant-for-listing/CreateApplicantForListing.tsx
> UTH-33: render warning if districts mismatch

- packages/frontend/src/pages/ParkingSpace/components/AllApplicantsTabContext.tsx
- packages/frontend/src/pages/ParkingSpace/components/ParkingSpaceInfo.tsx
- packages/frontend/src/pages/ParkingSpaces/components/create-applicant-for-listing/CreateApplicantForListing.tsx
- packages/frontend/src/pages/ParkingSpaces/index.tsx
* Button has been moved to display above the applicants listing on the listing page. It's now only displayed if no offers has been created
* Minor design adjustments for the button
> Feat:UTH-120 Create Offer Button Adjustments

- packages/frontend/src/pages/ParkingSpaces/components/SyncInternalParkingSpaces.tsx
* The button used for fetching publiched parking spaces from XPand and saving them to OneCore now has a better name
> Feat:uth-143 Fetch Parking Space Rename

- packages/backend/package-lock.json
- packages/backend/package.json
- packages/backend/src/services/leasing-service/adapters/core-adapter.ts
- packages/backend/src/services/leasing-service/index.ts
- packages/frontend/src/pages/ParkingSpaces/components/create-applicant-for-listing/CreateApplicantForListing.tsx
> Feat:UTH-220 Handle Tenants with Leases that is About to End

- packages/frontend/src/pages/Residences/Residences.tsx
- Fixes UTH-171 by comparing the review time with the correct field :see_no_evil: 
- This change wants to go live together with fix/UTH-171-.... in onecore-leasing
> UTH-171: Compare lastUpdatedAt with reviewedAt in housing ref form

- packages/backend/.eslintrc
- packages/backend/package-lock.json
- packages/backend/package.json
- packages/backend/src/api.ts
- packages/backend/src/services/leasing-service/adapters/core-adapter.ts
- packages/backend/src/services/leasing-service/comments.ts
- packages/backend/src/services/leasing-service/routes.ts
- packages/frontend/package-lock.json
- packages/frontend/package.json
- packages/frontend/src/index.css
- packages/frontend/src/pages/ParkingSpace/components/CommentSection.tsx
- packages/frontend/src/pages/ParkingSpace/hooks/addCommentRequestErrors.ts
- packages/frontend/src/pages/ParkingSpace/hooks/removeCommentRequestErrors.ts
- packages/frontend/src/pages/ParkingSpace/hooks/useAddComment.ts
- packages/frontend/src/pages/ParkingSpace/hooks/useCommentThread.ts
- packages/frontend/src/pages/ParkingSpace/hooks/useRemoveComment.ts
- packages/frontend/src/pages/ParkingSpace/index.tsx
- packages/frontend/src/theme.ts
- CommentSection (tied to ParkingSpaces, but could theoretically be attached to anything that has a numeric ID.
- Anyone can add comments
- Anyone can delete their own comments
- ~~Move some styling etc out to CSS~~ Nah, as it turns out this has been requested as a temporary feature, so we'll do that if we actually DO end up re-using it.
- ~~Display errors, in the unlikely event...~~ We now raise a toast to errors!
- ~~Formatting? Keep at least newlines/etc as entered by the user?~~ Overkill, for the same reasons as mentioned above.
- ~~Periodically poll for new messages? Pretty much a bell and whistle, but also kinda low-hanging~~ Also overkill, but still kinda low-hanging... :)
> uth-239: CommentSection UI + backend
